// platforms/preact/libs/core/src/element-protocol/preact-element.tsx
/**
 * La implementación de Preact de `ElementProtocol` (#64).
 *
 * ─────────────────────────────────────────────────────────────────────────────
 * ES EL GEMELO DEL DE ANGULAR, Y LA COMPARACIÓN ES EL PUNTO.
 *
 * `AngularElement` necesita `createApplication` —asíncrono—, un `ApplicationRef`,
 * `attachView`/`detachView` y una cola de promesas para que un `update` en el
 * mismo tick que el `mount` no se pierda. Acá `render(vnode, host)` es síncrono
 * y el propio Preact lleva la reconciliación, así que la cola sobra: `mount`,
 * `update` y `destroy` terminan antes de devolver.
 *
 * **Eso no lo hace mejor: lo hace DISTINTO, y es exactamente lo que la épica #37
 * quería medir.** El contrato `ElementProtocol` aguanta los dos, y aguanta uno
 * asíncrono y uno síncrono sin cambiar de forma — que era la pregunta.
 *
 * ─────────────────────────────────────────────────────────────────────────────
 * `listo` EXISTE AUNQUE ACÁ SEA TRIVIAL, Y NO ES SIMETRÍA GRATUITA.
 *
 * Quien consume el adaptador no sabe de qué plataforma es —ése es el sentido de
 * que la interfaz viva en `vitals`—, así que un `await adaptador.listo` tiene que
 * compilar y hacer lo correcto en las dos. Devolver una promesa ya resuelta es la
 * verdad acá: cuando `mount` vuelve, el DOM ya está pintado.
 *
 * ─────────────────────────────────────────────────────────────────────────────
 * DESTROY DEVUELVE EL HOST COMO LO ENCONTRÓ, IGUAL QUE EN ANGULAR.
 *
 * `render(null, host)` desmonta el árbol de Preact pero **no toca** los nodos que
 * ya estaban dentro del host antes de montar —el SSR del CMS los pone ahí—. Se
 * cuentan al montar y se recorta a esa marca, que es el mismo corte que
 * `hijosAlMontar` hace del lado de Angular. Sin eso, `destroy()` afirma que
 * limpió mientras deja nodos pintados.
 */

import { render } from 'preact';
import type { ComponentType, VNode } from 'preact';
import type { ElementProtocol } from '@synergos/core';

export class PreactElement<P extends Record<string, unknown>> implements ElementProtocol {
  readonly tag: string;

  private readonly componente: ComponentType<P>;
  private host: HTMLElement | null = null;
  private props: Partial<P> = {};
  private hijosAlMontar = 0;

  constructor(tag: string, componente: ComponentType<P>) {
    this.tag = tag;
    this.componente = componente;
  }

  mount(host: HTMLElement, inputs: Record<string, unknown> = {}): void {
    if (this.host) return;
    this.host = host;
    this.hijosAlMontar = host.childNodes.length;
    this.props = inputs as Partial<P>;
    this.pintar();
  }

  update(inputs: Record<string, unknown>): void {
    // Se FUSIONA, no se reemplaza: `update({ tone })` no puede borrar el `text`
    // que vino en `mount`. Es la misma semántica que `setInput` de Angular, que
    // es lo que hace que el mismo llamador sirva para las dos.
    this.props = { ...this.props, ...(inputs as Partial<P>) };
    this.pintar();
  }

  destroy(): void {
    const host = this.host;
    if (!host) return;
    render(null, host);
    while (host.childNodes.length > this.hijosAlMontar) {
      host.removeChild(host.lastChild as ChildNode);
    }
    this.host = null;
    this.props = {};
  }

  /** Resuelta siempre: `render` de Preact es síncrono. Ver la cabecera. */
  get listo(): Promise<void> {
    return Promise.resolve();
  }

  private pintar(): void {
    if (!this.host) return;
    const Componente = this.componente;
    render(<Componente {...(this.props as P)} /> as VNode, this.host);
  }
}

/**
 * Registra el custom element y devuelve su adaptador — el gemelo de
 * `registrarElementoAngular`.
 *
 * ⚠ **ES EL ÚNICO SITIO DE ESTA PLATAFORMA QUE LLAMA A `customElements.define`**,
 * y la obligación 8 del contrato lo comprueba recorriendo `apps/`: un elemento
 * que registre por su cuenta rompe el build. Sin eso el adaptador existe y no
 * manda, que es cómo un contrato se queda de adorno sin que nada falle (#62).
 *
 * El camino por TAG y el IMPERATIVO son dos, y los dos hacen falta: el CMS emite
 * `<synergos-badge>` en el SSR y el navegador instancia por tag; `mount(host,
 * inputs)` es el que describe `ElementProtocol`. Acá el primero se construye CON
 * el segundo —la clase del custom element delega en un `PreactElement`— así que
 * hay un solo sitio donde se monta y la interfaz no es decorativa.
 *
 * La coerción de atributo→prop es de esta plataforma y no del contrato: Preact no
 * trae un `@angular/elements`, así que se hace acá y en un solo sitio. Un
 * atributo HTML siempre llega como cadena; quien sabe qué es cada clave es el
 * normalizador de `vitals/core/src/inputs/`, que el elemento ya usa — por eso
 * esto pasa la cadena tal cual y no adivina tipos.
 */
export function registrarElementoPreact<P extends Record<string, unknown>>(
  tag: string,
  componente: ComponentType<P>,
  atributos: readonly string[] = [],
): PreactElement<P> {
  const adaptador = new PreactElement<P>(tag, componente);

  if (!customElements.get(tag)) {
    customElements.define(
      tag,
      class extends HTMLElement {
        static readonly observedAttributes = atributos;

        private readonly propio = new PreactElement<P>(tag, componente);

        connectedCallback(): void {
          this.propio.mount(this, leerAtributos(this, atributos));
        }

        disconnectedCallback(): void {
          this.propio.destroy();
        }

        attributeChangedCallback(nombre: string, _viejo: string | null, nuevo: string | null): void {
          this.propio.update({ [nombre]: nuevo ?? undefined });
        }
      },
    );
  }

  return adaptador;
}

/** Los atributos presentes, como cadenas. Los ausentes NO se emiten. */
function leerAtributos(el: HTMLElement, atributos: readonly string[]): Record<string, unknown> {
  const salida: Record<string, unknown> = {};
  for (const nombre of atributos) {
    // Un atributo AUSENTE no es lo mismo que uno vacío, y la diferencia la
    // resuelve el normalizador con `undefined`. Emitir `null` haría que
    // `resolveConfigValue` lo tomara por un valor dado y pisara el del `config`.
    if (el.hasAttribute(nombre)) salida[nombre] = el.getAttribute(nombre);
  }
  return salida;
}

// platforms/angular/libs/core/src/element-protocol/angular-element.ts
/**
 * La implementación de Angular de `ElementProtocol` (#62, opción A).
 *
 * ─────────────────────────────────────────────────────────────────────────────
 * POR QUÉ ESTO EXISTE, Y QUÉ ESTABA MAL ANTES.
 *
 * `ElementProtocol` vive en `vitals/core/src/bridge/` y se presenta como *«the
 * interface that every framework must implement to register a Web Component»*.
 * Medido en #62: **no lo importaba nadie**. `grep -rn "ElementProtocol"` sobre
 * `platforms/` y `vitals/`, fuera de su propio fichero, devolvía cero — Angular
 * registraba con `createCustomElement` directo, en 127 `main.ts` idénticos.
 *
 * O sea una interfaz que afirmaba una obligación que la única plataforma viva no
 * cumplía, **en la capa agnóstica, que es donde la va a leer quien escriba la
 * segunda plataforma**. La regla 24: un contrato que no importa nadie no es un
 * contrato, es un comentario con sintaxis.
 *
 * La decisión fue **honrarlo**, y lo que lo hace posible es una medición: los
 * **127 de 127** `main.ts` tienen la MISMA forma —sólo cambian el orden de los
 * imports y el formato—. Un patrón repetido 127 veces sin variación no es un
 * patrón: es una función que nadie extrajo.
 *
 * ─────────────────────────────────────────────────────────────────────────────
 * EL REPARTO, PORQUE NO ES OBVIO Y ES LA PARTE DISCUTIBLE.
 *
 * Hay DOS caminos de montaje y los dos hacen falta:
 *
 *   - **Por TAG** (`customElements.define`) — es el de producción. El CMS emite
 *     `<synergos-badge>` en el SSR y el bundle registra el tag; el navegador
 *     hace el resto. Lo sigue haciendo `createCustomElement` de
 *     `@angular/elements`, y **eso no se toca**: resuelve la coerción de
 *     atributos a inputs, que es trabajo real y no es de este contrato.
 *   - **IMPERATIVO** (`mount(host, inputs)`) — es el que `ElementProtocol`
 *     describe: dado un host y unos valores, montá. No hay tag de por medio.
 *
 * `registrarElementoAngular` hace el primero **construyendo el segundo**, así
 * que el adaptador es UN sitio y la interfaz deja de ser decorativa. Lo que NO
 * se hizo, y va dicho en vez de insinuado: **no se reescribió el camino por tag
 * para que pase por `mount`**. Habría que derivar `observedAttributes` de
 * `element-inputs.json` y reimplementar la coerción que `@angular/elements` ya
 * hace bien — cambiar un camino que funciona en 127 elementos por uno propio,
 * para satisfacer una interfaz. El contrato se honra teniéndolo implementado y
 * siendo el único sitio por donde se registra; no exige ser la plomería.
 *
 * ─────────────────────────────────────────────────────────────────────────────
 * EL ORDEN, QUE ES DONDE ESTÁ EL DEFECTO FÁCIL.
 *
 * `mount` devuelve `void` y crear la aplicación de Angular es asíncrono. Un
 * `update` que llegue antes de que el componente exista **no puede perderse en
 * silencio**: sería la misma familia de defectos que este repo persigue —una
 * escritura que no ocurre y nadie lo dice—. Se encadena sobre la promesa del
 * montaje, así que `mount` → `update` → `destroy` se aplican en ese orden
 * aunque se llamen los tres en el mismo tick, y los inputs que llegaron
 * mientras montaba se aplican al terminar.
 */

import {
  ApplicationConfig,
  ApplicationRef,
  ComponentRef,
  Type,
  createComponent,
} from '@angular/core';
import { createApplication } from '@angular/platform-browser';
import { createCustomElement } from '@angular/elements';
import type { ElementProtocol } from '@synergos/vitals-core';

/**
 * El adaptador de montaje de Angular.
 *
 * Es lo único de esta plataforma que implementa `ElementProtocol`, y por eso
 * el gate de #62 lo busca acá: un adaptador por plataforma, no uno por
 * elemento.
 */
export class AngularElement<T> implements ElementProtocol {
  readonly tag: string;

  private readonly componente: Type<T>;
  private readonly config: ApplicationConfig;

  /** La cola. Todo lo que hace este adaptador se encadena acá. */
  private pendiente: Promise<void> = Promise.resolve();

  private app: ApplicationRef | null = null;
  private ref: ComponentRef<T> | null = null;

  /**
   * Cuántos hijos tenía el host ANTES de montar.
   *
   * `createComponent` con un `hostElement` que no creó Angular renderiza dentro
   * y **no lo vacía al destruir** — con razón: el host es de quien lo pasó, y
   * borrarlo entero se llevaría por delante lo que el CMS dejó ahí en el SSR.
   * Así que se destruye lo que ESTE adaptador añadió y nada más. Sin esto,
   * `destroy()` dejaba el DOM pintado y decía que había limpiado.
   */
  private hijosAlMontar = 0;

  constructor(tag: string, componente: Type<T>, config: ApplicationConfig) {
    this.tag = tag;
    this.componente = componente;
    this.config = config;
  }

  mount(host: HTMLElement, inputs: Record<string, unknown> = {}): void {
    this.encolar(async () => {
      if (this.ref) return; // montar dos veces es un no-op, no un segundo componente.

      this.hijosAlMontar = host.childNodes.length;
      this.app = await createApplication(this.config);
      this.ref = createComponent(this.componente, {
        environmentInjector: this.app.injector,
        hostElement: host,
      });
      this.aplicar(inputs);
      this.app.attachView(this.ref.hostView);
      await this.estable();
    });
  }

  update(inputs: Record<string, unknown>): void {
    // Sobre la cola: un update antes de que el montaje termine se aplica al
    // terminar, no se pierde. Perderlo dejaría el elemento pintado con los
    // valores de arranque y nada lo diría.
    this.encolar(async () => {
      this.aplicar(inputs);
      await this.estable();
    });
  }

  destroy(): void {
    this.encolar(async () => {
      const host = this.ref?.location.nativeElement as HTMLElement | undefined;

      if (this.ref && this.app) this.app.detachView(this.ref.hostView);
      this.ref?.destroy();
      this.app?.destroy();

      // Lo que añadimos, y sólo eso. Ver `hijosAlMontar`.
      while (host && host.childNodes.length > this.hijosAlMontar) {
        host.removeChild(host.lastChild!);
      }

      this.ref = null;
      this.app = null;
    });
  }

  /** Para quien necesite esperar — los tests, y quien monte y mida. */
  get listo(): Promise<void> {
    return this.pendiente;
  }

  private encolar(paso: () => Promise<void>): void {
    this.pendiente = this.pendiente.then(paso);
  }

  /**
   * Espera a que el DOM refleje lo que se acaba de pedir.
   *
   * Sin esto, `listo` significaba «Angular ya creó el componente» y no «el
   * elemento está pintado»: con detección de cambios sin zonas, el `setInput`
   * marca sucio y el render llega después. Quien monta para medir —o para
   * mirarlo— leía un DOM vacío y no tenía forma de saber que era pronto.
   */
  private async estable(): Promise<void> {
    this.ref?.changeDetectorRef.detectChanges();
    await this.app?.whenStable();
  }

  private aplicar(inputs: Record<string, unknown>): void {
    if (!this.ref) return;
    for (const [nombre, valor] of Object.entries(inputs)) {
      this.ref.setInput(nombre, valor);
    }
  }
}

/**
 * Registra el custom element de un elemento de Angular.
 *
 * Es lo que llaman los 127 `main.ts`, y el único sitio de la plataforma donde
 * se llama a `customElements.define`. Devuelve el adaptador para que quien
 * monte imperativamente —un banco de pruebas, un host sin tag— tenga por dónde.
 *
 * **Registrar dos veces no redefine**: `customElements.define` lanza si el tag
 * ya existe, y el `main.ts` de cada elemento ya lo comprobaba. Ese `if` vivía
 * repetido 127 veces; ahora vive una.
 */
export function registrarElementoAngular<T>(
  tag: string,
  componente: Type<T>,
  config: ApplicationConfig,
): AngularElement<T> {
  const adaptador = new AngularElement(tag, componente, config);

  if (!customElements.get(tag)) {
    createApplication(config).then((appRef) => {
      // Se vuelve a mirar DESPUÉS del await: entre la comprobación de arriba y
      // este punto pudo registrarlo otro bundle que cargó a la vez. Sin esto,
      // `define` lanza y el elemento no monta — con el de arriba solo, la
      // carrera existe porque `createApplication` es asíncrono.
      if (customElements.get(tag)) return;
      customElements.define(tag, createCustomElement(componente, { injector: appRef.injector }));
    });
  }

  return adaptador;
}
